version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: log430
      POSTGRES_PASSWORD: laboratoire
      POSTGRES_DB: log430
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  web1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://log430:laboratoire@db:5432/log430
    volumes:
      - ./src:/app
    restart: always
    expose:
      - "5000"

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://log430:laboratoire@db:5432/log430
    volumes:
      - ./src:/app
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    depends_on:
      - web1
      - web2
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgresql://log430:laboratoire@db:5432/log430
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./src:/app
  #   restart: always

volumes:
  db:
  grafana_data:
