#!/bin/bash

# Script de finalisation et de test complet du système LOG430

echo "=========================================="
echo "=== FINALISATION DU SYSTÈME LOG430 ==="
echo "=========================================="

echo "Date: $(date)"
echo ""

echo "1. COMMIT ET PUSH DES MODIFICATIONS"
echo "===================================="
git add .
git status
echo ""
echo "Commit des modifications..."
git commit -m "Fix: Correction du customer-service - Login fonctionnel avec seed data complet"
echo ""
echo "Push vers le repository..."
git push origin lab5

echo ""
echo "2. VÉRIFICATION DE L'ÉTAT DU SYSTÈME LOCAL"
echo "=========================================="
echo "Conteneurs Docker:"
docker-compose -f docker-compose-microservices.yml ps

echo ""
echo "3. VÉRIFICATION DES SERVICES"
echo "============================"
echo "✓ API Gateway:" 
curl -s http://localhost:5000/health | grep -o "healthy\|OK" || echo "❌ ECHEC"

echo "✓ Customer Service:"
curl -s http://localhost:5005/health | grep -o "healthy\|OK" || echo "❌ ECHEC"

echo "✓ Store Service:"
curl -s http://localhost:5001/health | grep -o "healthy\|OK" || echo "❌ ECHEC"

echo "✓ Product Service:"
curl -s http://localhost:5002/health | grep -o "healthy\|OK" || echo "❌ ECHEC"

echo "✓ Sales Service:"
curl -s http://localhost:5003/health | grep -o "healthy\|OK" || echo "❌ ECHEC"

echo "✓ Inventory Service:"
curl -s http://localhost:5004/health | grep -o "healthy\|OK" || echo "❌ ECHEC"

echo "✓ Cart Service:"
curl -s http://localhost:5006/health | grep -o "healthy\|OK" || echo "❌ ECHEC"

echo "✓ Checkout Service:"
curl -s http://localhost:5007/health | grep -o "healthy\|OK" || echo "❌ ECHEC"

echo ""
echo "4. VÉRIFICATION DES DONNÉES"
echo "=========================="
echo "✓ Stores:" 
curl -s "http://localhost:5001/api/stores" | grep -o '"name":' | wc -l | tr -d ' ' | xargs echo "magasins trouvés"

echo "✓ Products:"
curl -s "http://localhost:5002/api/products/store/1" | grep -o '"name":' | wc -l | tr -d ' ' | xargs echo "produits trouvés"

echo "✓ Login Test:"
curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer Supermarcher22102002" \
  -d '{"email": "gestionnaire@maisonmere.com", "password": "gestionnaire123"}' \
  http://localhost:5005/api/customers/login | grep -o "Connexion réussie\|successful" && echo "✅ LOGIN OK" || echo "❌ LOGIN ECHEC"

echo ""
echo "=========================================="
echo "=== INSTRUCTIONS POUR LA VM ==="
echo "=========================================="
echo ""
echo "Maintenant, connectez-vous à la VM et exécutez :"
echo ""
echo "1. Arrêter tous les conteneurs:"
echo "   docker-compose -f docker-compose-microservices.yml down"
echo ""
echo "2. Supprimer les volumes (optionnel, pour reset complet):"
echo "   docker volume prune -f"
echo ""
echo "3. Récupérer les dernières modifications:"
echo "   git pull origin lab5"
echo ""
echo "4. Reconstruire et relancer tous les services:"
echo "   docker-compose -f docker-compose-microservices.yml up --build -d"
echo ""
echo "5. Attendre que tous les services soient up (30-60 secondes):"
echo "   docker-compose -f docker-compose-microservices.yml ps"
echo ""
echo "6. Lancer le test complet:"
echo "   ./test_vm_complete.sh"
echo ""
echo "=========================================="
echo "=== CHECKLIST FINALE ==="
echo "=========================================="
echo ""
echo "□ Tous les conteneurs sont 'Up'"
echo "□ API Gateway accessible (http://VM_IP:5000)"
echo "□ Login fonctionnel avec:"
echo "  - gestionnaire@maisonmere.com / gestionnaire123"
echo "  - employe@magasin1.com / employe123"
echo "  - client1@test.com / client123"
echo "□ Données visibles:"
echo "  - 3 magasins"
echo "  - 15 produits par magasin"
echo "  - 4 utilisateurs"
echo "□ Tous les services health OK"
echo "□ Navigation fonctionnelle"
echo ""
echo "=========================================="
echo "=== ACTEURS ET CAS D'USAGE ==="
echo "=========================================="
echo ""
echo "1. GESTIONNAIRE MAISON MÈRE (gestionnaire@maisonmere.com)"
echo "   - UC1: Consulter les rapports de ventes"
echo "   - UC3: Gérer les produits"
echo "   - UC8: Paramétrer les seuils de réapprovisionnement"
echo ""
echo "2. EMPLOYÉ MAGASIN (employe@magasin1.com)"
echo "   - UC2: Enregistrer une vente"
echo "   - UC4: Consulter l'inventaire"
echo "   - UC5: Demander un réapprovisionnement"
echo ""
echo "3. RESPONSABLE LOGISTIQUE (logistique@centre.com)"
echo "   - UC6: Traiter les demandes de réapprovisionnement"
echo "   - UC7: Gérer les stocks"
echo ""
echo "4. CLIENT (client1@test.com)"
echo "   - Navigation des produits"
echo "   - Panier d'achat"
echo "   - Commande en ligne"
echo ""
echo "=========================================="
echo "=== SERVICES DISPONIBLES ==="
echo "=========================================="
echo ""
echo "URL Base: http://VM_IP:5000"
echo "Token API: Supermarcher22102002"
echo ""
echo "- /stores - Gestion des magasins"
echo "- /products - Catalogue produits"
echo "- /sales - Rapports de ventes"
echo "- /inventory - Gestion inventaire"
echo "- /cart - Panier d'achat"
echo "- /login - Connexion"
echo "- /health-status - État des services"
echo ""
echo "=========================================="
echo "=== FINALISATION TERMINÉE ==="
echo "=========================================="
echo ""
echo "Le système est maintenant prêt pour les tests finaux sur la VM."
echo "Toutes les corrections ont été appliquées et commitées."
echo ""
