events {}

http {
    upstream flask_backend {
        server web1:5000;
        server web2:5000;
    }

    server {
        listen 80;

        # Trafic principal load balancé entre web1 et web2
        location / {
            proxy_pass http://flask_backend;
        }

        # Pour exposer les métriques Prometheus (pris depuis web1 uniquement)
        location /metrics {
            proxy_pass http://web1:5000/metrics;
        }
    }
}
